### ISSUE TITLE
"rsync__auto: false" seemingly ignored

### ISSUE THREAD

**Issue by FlorinAndrei** [smerrill/vagrant-rsync-back#2]
I have:

```
    config.vm.synced_folder "files", "/vagrant", type: "rsync",
            rsync__exclude: [".git/", ".idea/"],
            rsync__auto: false
```

However, when I do "vagrant up", I still get:

```
    ==> default: Rsyncing folder: /home/florin/vagrant/aws-qa/files/ => /vagrant
```

Is that normal, or is it a side-effect of using vagrant-rsync-back? (I'm very new to Vagrant so that's why I'm asking.)

This is a regular automatic rsync _forward_ done by Vagrant when up-ing the instance; it's not an (automatic) rsync-back.

I'm using the aws provider if that makes any difference.

**Comment by sidneygijzen** [comment]
vagrant-rsync-back only initiates when you call it manually on the command line. It doesn't do anything on `vagrant up` (AFAIK). So, I think this issue should be moved to the vagrant issue queue.

**Comment by smerrill** [comment]
@sidneygijzen is correct. This plugin only implements a command. It does not hook into any other part of the Vagrant lifecycle.
